### PR TITLE
Annotae Grid and List return types explicitly to avoid redundant inlined inferred types

### PR DESCRIPTION
**Pull request by Andarist**
fixes https://github.com/bvaughn/react-window/issues/875

### CODE REVIEW

**Comment by bvaughn** [comment]
Wow! This is very kind of you. Thanks, @Andarist!

**Comment by bvaughn** [comment]
Just tested this and it works with React 18.3+ and 19.0+ but it fails with React <= 18.2:
```
src/App.tsx:15:25 - error TS2339: Property 'index' does not exist on type '{}'.

15 function RowComponent({ index, style }: RowComponentProps<object>) {
```
The underlying cause of which is:
```
Module '"react"' has no exported member 'JSX'.ts(2305)
```
Replacing the `JSX` return type with `ReactElement<any, any>` causes a different underlying issue for `CellComponentProps` and `RowComponentProps` that also breaks the build:
```
Type 'ReactNode' is not assignable to type 'ReactElement<any, any> | null'.
```
Though I think that one can be fixed by changing the return type annotation for `cellComponent` and `rowComponent` to also be `ReactElement`.

**Comment by Andarist** [comment]
> Wow! This is very kind of you. Thanks, @Andarist!

Always happy to help out :)
