### ISSUE TITLE
tsc error with 2.2.1

### ISSUE THREAD

**Issue by drodil** [bvaughn/react-window#875]
After updating to 2.2.1 from 2.0.2 I get the following tsc error:

```
node_modules/react-window/dist/react-window.d.ts:23:10 - error TS2724: '"react"' has no exported member named 'ToggleEventHandler'. Did you mean 'EventHandler'?

23 import { ToggleEventHandler } from 'react';
            ~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/react-window/dist/react-window.d.ts:23
```
Any clue why this is happening? React version is 18.3.1.

**Comment by bvaughn** [comment]
I don't know why you're seeing this specifically, because I don't see it when I make a test project using `react@18.3.1` (and `@types/react@18.3.1`). It does look like the `ToggleEventHandler` type was added in React 19 (types) but ideally that shouldn't really matter. I think the only reason it's even included in this project at all is from my attempt to allow people to pass additional, arbitrary DOM attributes to `List` and `Grid`. I'm not sure of the best way to support that while also avoiding having those extra attributes inlined into my type definitions file.

**Comment by bvaughn** [comment]
Hey @Andarist I wonder if yo have any ideas here? (Also feel free to ignore this if you're busy.)

**Comment by bvaughn** [comment]
This issue has been fixed in #876 and released in version 2.2.2

Thanks for the assist, @Andarist!
