### ISSUE TITLE
Module '"react-window"' has no exported member 'ListOnItemsRenderedProps'

### ISSUE THREAD

**Issue by jiangxiaoqiang** [bvaughn/react-window#881]
when I migrate the react window from 1.8.11 to 2.0.0, shows error:

```
src/component/common/previewer/doc/MemoizedPDFPreview.tsx:14:3 - error TS2305: Module '"react-window"' has no exported member 'ListOnItemsRenderedProps'.

14   ListOnItemsRenderedProps,
     ~~~~~~~~~~~~~~~~~~~~~~~~

src/component/common/previewer/doc/MemoizedPDFPreview.tsx:15:3 - error TS2305: Module '"react-window"' has no exported member 'ListOnScrollProps'.

15   ListOnScrollProps,
```

I have to rewrite the code? or any migration guide?

**Comment by bvaughn** [comment]
Have you read the docs? There are examples of this stuff in the docs.

There are also examples of how to migrate from version 1 to 2 and the change log

**Comment by jiangxiaoqiang** [comment]
Yes I have read docs from https://react-window.vercel.app/, seems the new style completely different with the 1.x, and did not found the migration guide from official site or google or npm repository https://www.npmjs.com/package/react-window/v/2.0.0.

**Comment by bvaughn** [comment]
https://github.com/bvaughn/react-window/blob/master/CHANGELOG.md#upgrade-path

**Comment by bvaughn** [comment]
If you have suggestions for how I can make this easier to find, I’m open to ideas.

**Comment by jiangxiaoqiang** [comment]
Maybe you can put the migration guide to the 2.0.0 release page or the website to introduce the change. I think it's better to told the imcompatible warning in the official site. just advice
